### ISSUE TITLE
The variable name is sendCert but it takes Partnership.PTYPE_RECEIVER

### ISSUE THREAD

**Issue by gaochenyue** [OpenAS2/OpenAs2App#174]
https://github.com/OpenAS2/OpenAs2App/blob/db87f19197a2050199699e3ae7c0ef54f5fc4c4d/Server/src/main/java/org/openas2/util/AS2Util.java#L491

The variable name is sendCert but the method takes Partnership.PTYPE_RECEIVER. Should it take Partnership.PTYPE_SENDER?

**Comment by igwtech** [comment]
Hi,
   If I understand correctly, the reason it looks like this is because the
sender/receiver roles reverses when you process a MDN. The MDN is sent back
by the Recipient of the Message and signed with their Private Key for
non-repudiation verification purposes.
   So, maybe we could change the variable name to make it more clear we
need the Recipient's Certificate to verify the MDN signature.

-J

**Comment by gaochenyue** [comment]
Thank you for a quick response. I thought the same at first but I was confused by line 473 and 474. It you take a look at those two lines, you can see the mdn sender is set to the receiver of the AS2 msg. The mdn receiver is set to the sender (which is myself) of the AS2 msg. So if it get cert by Partnership.PTYPE_RECEIVER, it actually gets the cert of myself but it is supposed to get the MDN sender cert.

**Comment by uhurusurfa** [comment]
The confusion comes in because the sender becomes the receiever and the recevier the sender depending on if you are talking about an **AS2 Message** or an **MDN**.

A few things to note:

1. the Parnership object that is carried around is ALWAYS the one for **AS2 Message** sender to **AS2 Message** recevier (NOT for **MDN sender** to **MDN receiver** .
2. the receiver of the AS2 Message uses the certificate of the AS2 Message sender and the receiver of the MDN uses the certificate of the MDN sender)

For clarity lets say X is the sender of the **AS2 message** and Y is the receiver of the **AS2 message**.

The getCertificate method it invokes it does:
`getCertificate(getAlias(mdn.getPartnership(), partnershipType))`

So the receiver within the Partnership object returned from mdn.getPartnership() is the MDN sender because they were the receiuver of the AS2 message - in other words it retunrns the certifiace fot Y.

Since the method in reference is processing a received MDN and the call to parseMDN() wil need to verify the signed MDN, it must use the sender of the MDN's certificate - ie. Y's certificate.
In terms of using "senderCert", it is requiring the sender of the MDN's certificate in order to verify the signature so the name of the variable is appropriate.

So it is correct.

**Comment by gaochenyue** [comment]
Thank you for the explanation. I understand your point but I still think the implementation doesn't meet your expectation. The "from" and "to" are switched for the first time at Line 102-104 in AS2MDNReceiverHandler.java and then they are switched again at line 24-25 in AS2MessageMDN.java. Two switches just revert them to the original values. I raised this ticket because it threw exception of "unable to verify msg with the cert". After I changed it to Partnership.PTYPE_SENDER, it worked as expected. I could be wrong. Thank you again!

**Comment by igwtech** [comment]
Yes, there must be a problem with the configuration. I recently ran into a
problem that might be similar to your situation. OpenAS2 uses different
HTTP/S endpoints for receiving Messages and Async MDNs. Some AS2 Software
doesn't support this. Maybe your TP's software don't support this scenario,
try using Sync MDNs instead.

Regards, J

**Comment by gaochenyue** [comment]
Thank you all. I appreciate your answers. Let me double check my configuration.

**Comment by igwtech** [comment]
You are welcome! Let us know if you still have the problem.
