### ISSUE TITLE
MDN sent by OpenAS2 fails to be parsed by EDI Integrator Component from www.nsoftware.com

### ISSUE THREAD

**Issue by DevDef** [OpenAS2/OpenAs2App#69]
Hi,

I have an AS2 partner using a server sofware identified by the following User-Agent:
`EDI Integrator Component - www.nsoftware.com`
I can send him AS2 messages without any problems, but when he send (actually, I send from his Web configuration portal) a test message to my OpenAS2 server, the MDN received by the partner triggers the following exception:
`Sending document failed. Sending exception. No MIME-boundary found.( )`

I tried to tweak the parameters (content_transfer_encoding, compression_mode, prevent_cononicalization_for_mic, etc.), but it’s still failing with the same exception on the partner’s server.

Any hint would be welcome.

Regards,

Davy

**Comment by uhurusurfa** [comment]
Please post this in the OpenAS2 Discussions here so that other OpenAS2
users have a central place to find the solutions ot problems such as yours:
https://sourceforge.net/p/openas2/discussion/

**Comment by uhurusurfa** [comment]
This is my first bit of feedback on this issue which will be added to the
discussion board once you have created it there.

As a start my guess is that OpenAS2 is seeing some kind of issue with the
request and the MDN response is somehow not being sent as a multipart with
a MIME BODY PART boundary and the partners software is expecting a
multipart no matter what.

Turn TRACE level logging on in the OpenAS2 server.
If necessary, turn Mime Body Part Logging on in OpenAS2 (see section 13.7
by that name in the OpenAS2HowTo for the current release on how to do this)

**Comment by DevDef** [comment]
Here’s the SF thread: https://sourceforge.net/p/openas2/discussion/272857/thread/3c2fdd1c/
I will follow your suggestion about increasing log levels Monday…

**Comment by mikeflisher** [comment]
@DevDef are you using async mode for the MDN?

**Comment by DevDef** [comment]
Hi Mike,

Unfortunately, it’s synchronous MDN mode. But the common thing that we share is that we have an nginx reverse proxy in front of our OpenAS2 server…

**Comment by mikeflisher** [comment]
Header folding is enabled by default for OpenAS2 sync but it's probably worth checking your nginx error logs/tcpdump on nginx server interface and capture the request as it's passing through.

That's where we saw the async header wasn't being folded while trying to send async to RSSBus AS2Connect (which also used to be from nsoftware.) Can provide you some logs of this if it helps.

From the other thread, we also had some issues getting TRACE level logging working. This was because the `commons-logging.properties` file is read from the directory you start the java process. 

In the systemd unit file try setting the `WorkingDirectory=` to the bin folder. I recommend not running via systemd when debugging though but run openas2 manually starting `./start-openas2.sh` from within the bin folder and from the previous directory.

**Comment by DevDef** [comment]
Thanks for all your advice.
Concerning the log level, I consider it’s a bug that has to be fixed.

**Comment by uhurusurfa** [comment]
Try building your pwn deployment from the latest "dev" branch and see if it works.

**Comment by DevDef** [comment]
I’ve just tried: always the same error on the partner’s side! :-(

**Comment by DevDef** [comment]
Many thanks to Christopher aka uhurusurfa who has finally found a fix to this issue.

**Comment by HamzaDevz** [comment]
what was the issue ? I also want to send message to Transus but they cannot read the message.
